export enum ErrorCode {
  // Initialization errors
  SCENE_INIT_FAILED = 'SCENE_INIT_FAILED',
  RENDERER_INIT_FAILED = 'RENDERER_INIT_FAILED',
  RENDERER_NOT_INITIALIZED = 'RENDERER_NOT_INITIALIZED',
  CAMERA_INIT_FAILED = 'CAMERA_INIT_FAILED',
  WEBGL_NOT_SUPPORTED = 'WEBGL_NOT_SUPPORTED',
  INITIALIZATION_FAILED = 'INITIALIZATION_FAILED',
  PATH_TRACING_INIT_FAILED = 'PATH_TRACING_INIT_FAILED',
  
  // Loading errors
  MODEL_LOAD_FAILED = 'MODEL_LOAD_FAILED',
  TEXTURE_LOAD_FAILED = 'TEXTURE_LOAD_FAILED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  UNSUPPORTED_FORMAT = 'UNSUPPORTED_FORMAT',
  
  // Runtime errors
  INVALID_CONFIGURATION = 'INVALID_CONFIGURATION',
  RENDER_ERROR = 'RENDER_ERROR',
  RENDER_FAILED = 'RENDER_FAILED',
  SCENE_OPERATION_FAILED = 'SCENE_OPERATION_FAILED',
  
  // State errors
  COMPONENT_NOT_MOUNTED = 'COMPONENT_NOT_MOUNTED',
  INVALID_STATE = 'INVALID_STATE',
  
  // Parameter errors
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  
  // Operation errors
  OPERATION_FAILED = 'OPERATION_FAILED',
  
  // Unknown error
  UNKNOWN = 'UNKNOWN',
}