export enum ErrorCode {
  // Initialization errors
  SCENE_INIT_FAILED = 'SCENE_INIT_FAILED',
  RENDERER_INIT_FAILED = 'RENDERER_INIT_FAILED',
  CAMERA_INIT_FAILED = 'CAMERA_INIT_FAILED',
  WEBGL_NOT_SUPPORTED = 'WEBGL_NOT_SUPPORTED',
  
  // Loading errors
  MODEL_LOAD_FAILED = 'MODEL_LOAD_FAILED',
  TEXTURE_LOAD_FAILED = 'TEXTURE_LOAD_FAILED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  
  // Runtime errors
  INVALID_CONFIGURATION = 'INVALID_CONFIGURATION',
  RENDER_ERROR = 'RENDER_ERROR',
  
  // State errors
  COMPONENT_NOT_MOUNTED = 'COMPONENT_NOT_MOUNTED',
  
  // Unknown error
  UNKNOWN = 'UNKNOWN',
}